name: Deploy to Azure VM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 57.159.25.129
          username: azureuser
          key: ${{ secrets.AZURE_VM_PRIVATE_KEY }}
          passphrase: ${{ secrets.AZURE_SSH_PASSPHRASE }}
          port: 22
          script: |
            cd /home/azureuser/zenithive-leaderboard-backend
            git pull origin main
            npm install
             pm2 restart zenithive-backend
